import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Muhammadnozim',
      email: 'admin@example.com',
      password: bcrypt.hashSync('reactjs01'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Qizil kurtka',
      slug: 'free-shirt',
      category: 'Kurtkalar',
      image: '/images/namuna.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Eng ommabop va sifatli mahsulotlardan biri aynan mana shu kurtka hisoblanadi!',
    },
    {
      name: 'Qizil kurtka',
      slug: 'free-shirt',
      category: 'Futbolkalar',
      image: '/images/namuna.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Eng ommabop va sifatli mahsulotlardan biri aynan mana shu kurtka hisoblanadi!',
    },
    {
      name: 'Qizil kurtka',
      slug: 'free-shirt',
      category: "Ko'ylaklar",
      image: '/images/namuna.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Eng ommabop va sifatli mahsulotlardan biri aynan mana shu kurtka hisoblanadi!',
    },
    {
      name: 'Qizil kurtka',
      slug: 'free-shirt',
      category: "Poyabzallar",
      image: '/images/namuna.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Eng ommabop va sifatli mahsulotlardan biri aynan mana shu kurtka hisoblanadi!',
    },
    {
      name: 'Qizil kurtka',
      slug: 'free-shirt',
      category: "Sviterlar",
      image: '/images/namuna.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Eng ommabop va sifatli mahsulotlardan biri aynan mana shu kurtka hisoblanadi!',
    },
    {
      name: 'Qizil kurtka',
      slug: 'free-shirt',
      category: "Qalpoqlar",
      image: '/images/namuna.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Eng ommabop va sifatli mahsulotlardan biri aynan mana shu kurtka hisoblanadi!',
    },
    {
      name: 'Qizil kurtka',
      slug: 'free-shirt',
      category: "Paypoqlar",
      image: '/images/namuna.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Eng ommabop va sifatli mahsulotlardan biri aynan mana shu kurtka hisoblanadi!',
    },
    {
      name: 'Qizil kurtka',
      slug: 'free-shirt',
      category: "Qo'lqoplar",
      image: '/images/namuna.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Eng ommabop va sifatli mahsulotlardan biri aynan mana shu kurtka hisoblanadi!',
    },
    {
      name: 'Qizil kurtka',
      slug: 'free-shirt',
      category: "Kastyumlar",
      image: '/images/namuna.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Eng ommabop va sifatli mahsulotlardan biri aynan mana shu kurtka hisoblanadi!',
    },
  ],
}

export default data
